var informix = require('informixdb')
    , connStr = require('./conexiondb')

informix.open(connStr.ifxdbs, function (err, conn) {
    conn.querySync("create table certificados (nro_certif serial primary key, emision date, cantidad smallint, nro_socio integer)")
    conn.querySync("insert into certificados VALUES (1,'31/07/2008',19,1)")
    conn.querySync("insert into certificados VALUES (2,'09/02/2019',1,1)")
    conn.querySync("insert into certificados VALUES (3,'19/07/2010',3,1)")
    conn.querySync("insert into certificados VALUES (5,'21/11/2011',1,2)")
    conn.querySync("insert into certificados VALUES (6,'11/01/2019',1,3)")
    conn.querySync("insert into certificados VALUES (7,'06/01/2014',2,3)")
    conn.querySync("insert into certificados VALUES (4,'21/11/2019',1,5)")
    conn.querySync("insert into certificados VALUES (8,'04/12/2019',1,4)")
    conn.querySync("insert into certificados VALUES (9,'23/01/2019',1,4)")
    conn.querySync("insert into certificados VALUES (10,'23/12/2016',5,4)")
    conn.querySync("insert into certificados VALUES (11,'16/01/2018',1,7)")
    conn.querySync("insert into certificados VALUES (12,'10/01/2019',2,6)")
    conn.querySync("insert into certificados VALUES (13,'16/12/2019',3,7)")
    var stmt = conn.prepareSync("select * from certificados")
    var result = stmt.executeSync()
    var data = result.fetchAllSync()
    console.log("Fetched data = ", data)
    result.closeSync()
    //conn.querySync("drop table certificados")
    conn.closeSync()
})